# Generated by Django 5.2.5 on 2025-08-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = []
